language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

env:
    - REQUIREMENTS="Django==1.6.9 South==1.0"
    - REQUIREMENTS="Django==1.7.7"
    - REQUIREMENTS="Django==1.8.7"

cache: pip

install:
    - pip install $REQUIREMENTS
    - pip install django-tagging==0.3.6
    - pip install django-pagination-py3
    - pip install feedparser
    - pip install pinax-theme-bootstrap
    - pip install beautifulsoup4
    - pip install coverage==3.6
    - pip install python-coveralls==2.4.0
    - pip install factory-boy==2.5.0
    - pip install mock
    - export PYTHONPATH=.

before_script: coverage erase

script: coverage run --source=planet manage.py test --settings=testsettings

after_success: coverage report; coveralls
